# Setup
title:        FourMB
tagline:      because it's enough
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Amrit Twanabasu
  url:        http://amrittwanabasu.com.np

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

